pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        google()
        mavenCentral()
        maven {
            url = "https://jitpack.io"
            content {
                includeGroup "com.github.ybq"
                includeGroup "com.github.iBotPeaches.smali"
            }
        }
    }
}

rootProject.name = 'Apk Repacker Revived'
include ':app'
include ':common'
include ':colorpicker'
include ':expandablerecyclerview'
include ':photoview'
include ':vectormaster'
include ':codeeditor'
