// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: C:/Users/Yaroslav/Desktop/Project/jflex-1.8.2/examples/simple/src/main/jflex/Scanner_mtd.flex

package com.riyadm.apkrepacker.autotranslator.dictionary

import java.io.IOException
import java.io.InputStream
import java.io.InputStreamReader
import java.io.Reader


// See https://github.com/jflex-de/jflex/issues/222
open class Scanner(
    /**
     * Input device.
     */
    private var zzReader: Reader?
) {

    @JvmField
    protected var m_String = StringBuffer()

    /**
     * Current state of the DFA.
     */
    private var zzState = 0

    /**
     * Current lexical state.
     */
    private var zzLexicalState = YYINITIAL

    /**
     * This buffer contains the current text to be matched and is the source of the [yytext]
     * string.
     */
    private var zzBuffer = CharArray(ZZ_BUFFERSIZE)

    /**
     * Text position at the last accepting state.
     */
    private var zzMarkedPos = 0

    /**
     * Current text position in the buffer.
     */
    private var zzCurrentPos = 0

    /**
     * Marks the beginning of the [yytext] string in the buffer.
     */
    private var zzStartRead = 0

    /**
     * Marks the last character in the buffer, that has been read from input.
     */
    private var zzEndRead = 0

    /**
     * Whether the scanner is at the end of file.
     *
     * @see yyatEOF
     */
    private var zzAtEOF = false

    /**
     * The number of occupied positions in [zzBuffer] beyond [zzEndRead].
     *
     * When a lead/high surrogate has been read from the input stream into the final
     * [zzBuffer] position, this will have a value of 1; otherwise, it will have a value of 0.
     */
    private var zzFinalHighSurrogate = 0

    /**
     * Number of newlines encountered up to the start of the matched text.
     */
    @Suppress("unused")
    private var yyline = 0

    /**
     * Number of characters from the last newline up to the start of the matched text.
     */
    @Suppress("unused")
    private var yycolumn = 0

    /**
     * Number of characters up to the start of the matched text.
     */
    @Suppress("unused")
    private var yychar: Long = 0

    /**
     * Whether the scanner is currently at the beginning of a line.
     */
    @Suppress("unused")
    private var zzAtBOL = true

    /**
     * Whether the user-EOF-code has already been executed.
     */
    private var zzEOFDone = false

    constructor(r: InputStream) : this(InputStreamReader(r))

    /**
     * Refills the input buffer.
     *
     * @return `false` iff there was new input.
     * @throws IOException if any I/O-Error occurs
     */
    @Throws(IOException::class)
    private fun zzRefill(): Boolean {

        /* first: make room (if you can) */
        if (zzStartRead > 0) {
            zzEndRead += zzFinalHighSurrogate
            zzFinalHighSurrogate = 0
            System.arraycopy(
                zzBuffer, zzStartRead,
                zzBuffer, 0,
                zzEndRead - zzStartRead
            )

            /* translate stored positions */
            zzEndRead -= zzStartRead
            zzCurrentPos -= zzStartRead
            zzMarkedPos -= zzStartRead
            zzStartRead = 0
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.size - zzFinalHighSurrogate) {
            /* if not: blow it up */
            val newBuffer = CharArray(zzBuffer.size * 2)
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.size)
            zzBuffer = newBuffer
            zzEndRead += zzFinalHighSurrogate
            zzFinalHighSurrogate = 0
        }

        /* fill the buffer with new input */
        val requested = zzBuffer.size - zzEndRead
        val numRead = zzReader!!.read(zzBuffer, zzEndRead, requested)

        /* not supposed to occur according to specification of java.io.Reader */
        if (numRead == 0) {
            throw IOException(
                "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround."
            )
        }
        if (numRead > 0) {
            zzEndRead += numRead
            if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
                if (numRead == requested) { // We requested too few chars to encode a full Unicode character
                    --zzEndRead
                    zzFinalHighSurrogate = 1
                } else {                    // There is room in the buffer for at least one more char
                    val c = zzReader!!.read()  // Expecting to read a paired low surrogate char
                    if (c == -1) {
                        return true
                    } else {
                        zzBuffer[zzEndRead++] = c.toChar()
                    }
                }
            }
            /* potentially more input available */
            return false
        }

        /* numRead < 0 ==> end of stream */
        return true
    }

    /**
     * Closes the input reader.
     *
     * @throws IOException if the reader could not be closed.
     */
    @Throws(IOException::class)
    fun yyclose() {
        zzAtEOF = true // indicate end of file
        zzEndRead = zzStartRead // invalidate buffer

        if (zzReader != null) {
            zzReader!!.close()
        }
    }

    /**
     * Resets the scanner to read from a new input stream.
     *
     * Does not close the old reader.
     *
     * All internal variables are reset, the old input stream **cannot** be reused (internal
     * buffer is discarded and lost). Lexical state is set to `ZZ_INITIAL`.
     *
     * Internal scan buffer is resized down to its initial length, if it has grown.
     *
     * @param reader The new input stream.
     */
    fun yyreset(reader: Reader?) {
        zzReader = reader
        zzEOFDone = false
        yyResetPosition()
        zzLexicalState = YYINITIAL
        if (zzBuffer.size > ZZ_BUFFERSIZE) {
            zzBuffer = CharArray(ZZ_BUFFERSIZE)
        }
    }

    /**
     * Resets the input position.
     */
    private fun yyResetPosition() {
        zzAtBOL = true
        zzAtEOF = false
        zzCurrentPos = 0
        zzMarkedPos = 0
        zzStartRead = 0
        zzEndRead = 0
        zzFinalHighSurrogate = 0
        yyline = 0
        yycolumn = 0
        yychar = 0L
    }

    /**
     * Returns whether the scanner has reached the end of the reader it reads from.
     *
     * @return whether the scanner has reached EOF.
     */
    fun yyatEOF(): Boolean {
        return zzAtEOF
    }

    /**
     * Returns the current lexical state.
     *
     * @return the current lexical state.
     */
    fun yystate(): Int {
        return zzLexicalState
    }

    /**
     * Enters a new lexical state.
     *
     * @param newState the new lexical state
     */
    fun yybegin(newState: Int) {
        zzLexicalState = newState
    }

    /**
     * Returns the text matched by the current regular expression.
     *
     * @return the matched text.
     */
    fun yytext(): String {
        return String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead)
    }

    /**
     * Returns the character at the given position from the matched text.
     *
     * It is equivalent to `yytext().charAt(pos)`, but faster.
     *
     * @param position the position of the character to fetch. A value from 0 to `yylength()-1`.
     * @return the character at `position`.
     */
    fun yycharat(position: Int): Char {
        return zzBuffer[zzStartRead + position]
    }

    /**
     * How many characters were matched.
     *
     * @return the length of the matched text region.
     */
    fun yylength(): Int {
        return zzMarkedPos - zzStartRead
    }

    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * They will be read again by then next call of the scanning method.
     *
     * @param number the number of characters to be read again. This number must not be greater than
     * [yylength].
     */
    open fun yypushback(number: Int) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG)

        zzMarkedPos -= number
    }


    /**
     * Contains user EOF-code, which will be executed exactly once,
     * when the end of file is reached
     */
    @Throws(IOException::class)
    private fun zzDoEOF() {
        if (!zzEOFDone) {
            zzEOFDone = true

            yyclose()
        }
    }

    @Throws(Exception::class)
    fun checkToken(str: String) {
        val token = next_token()
        if (token != str) {
            throw Exception(String.format("Invalid token: expected=%s, got=%s", str, token))
        }
    }

    /**
     * Resumes scanning until the next regular expression is matched, the end of input is encountered
     * or an I/O-Error occurs.
     *
     * @return the next token.
     * @throws IOException if any I/O-Error occurs.
     */
    @Throws(IOException::class)
    open fun next_token(): String {
        var zzInput = 0
        var zzAction: Int

        // cached fields:
        var zzCurrentPosL: Int
        var zzMarkedPosL: Int
        var zzEndReadL = zzEndRead
        var zzBufferL = zzBuffer

        val zzTransL = ZZ_TRANS
        val zzRowMapL = ZZ_ROWMAP
        val zzAttrL = ZZ_ATTRIBUTE

        while (true) {
            zzMarkedPosL = zzMarkedPos

            zzAction = -1

            zzStartRead = zzMarkedPosL
            zzCurrentPos = zzStartRead
            zzCurrentPosL = zzCurrentPos

            zzState = ZZ_LEXSTATE[zzLexicalState]

            // set up zzAction for empty match case:
            var zzAttributes = zzAttrL[zzState]
            if ((zzAttributes and 1) == 1) {
                zzAction = zzState
            }


            zzForAction@ while (true) {

                if (zzCurrentPosL < zzEndReadL) {
                    zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL)
                    zzCurrentPosL += Character.charCount(zzInput)
                } else if (zzAtEOF) {
                    zzInput = YYEOF
                    break@zzForAction
                } else {
                    // store back cached positions
                    zzCurrentPos = zzCurrentPosL
                    zzMarkedPos = zzMarkedPosL
                    val eof = zzRefill()
                    // get translated positions and possibly new buffer
                    zzCurrentPosL = zzCurrentPos
                    zzMarkedPosL = zzMarkedPos
                    zzBufferL = zzBuffer
                    zzEndReadL = zzEndRead
                    if (eof) {
                        zzInput = YYEOF
                        break@zzForAction
                    } else {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL)
                        zzCurrentPosL += Character.charCount(zzInput)
                    }
                }
                val zzNext = zzTransL[zzRowMapL[zzState] + zzCMap(zzInput)]
                if (zzNext == -1) break@zzForAction
                zzState = zzNext

                zzAttributes = zzAttrL[zzState]
                if ((zzAttributes and 1) == 1) {
                    zzAction = zzState
                    zzMarkedPosL = zzCurrentPosL
                    if ((zzAttributes and 8) == 8) break@zzForAction
                }

            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL

            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true
                zzDoEOF()
                run {
                    return ""
                    //return "\n";
                    // return m_SF.newSymbol("EOF", sym.EOF);
                }
            } else {
                when (if (zzAction < 0) zzAction else ZZ_ACTION[zzAction]) {
                    1 -> {
                        System.err.println("Illegal character: " + yytext())
                    }
                    2 -> { /* ignore white space. */
                    }
                    3 -> {
                        m_String.setLength(0)
                        yybegin(STRING)
                    }
                    4 -> {
                        // break;
                        return "{" // m_SF.newSymbol("Left curly bracket", sym.LCURLY);
                    }
                    5 -> {
                        // break;
                        return "}"
                        //m_SF.newSymbol("Right curly bracket", sym.RCURLY);
                    }
                    6 -> {
                        m_String.append(yytext())
                    }
                    7 -> {
                        yybegin(YYINITIAL)
                        return m_String.toString()
                    }
                    8 -> {
                        m_String.append('\\')
                    }
                    9 -> {
                        m_String.append('\"')
                    }
                    10 -> {
                        m_String.append('\b')
                    }
                    11 -> {
                        m_String.append('\u000C')
                    }
                    12 -> {
                        m_String.append('\n')
                    }
                    13 -> {
                        m_String.append('\r')
                    }
                    14 -> {
                        m_String.append('\t')
                    }
                    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28 -> {
                    }
                    else -> zzScanError(ZZ_NO_MATCH)
                }
            }
        }
    }

    companion object {
        /**
         * This character denotes the end of file.
         */
        const val YYEOF = -1

        // Lexical states.
        const val YYINITIAL = 0
        const val STRING = 2

        /**
         * Initial size of the lookahead buffer.
         */
        private const val ZZ_BUFFERSIZE = 16384

        /**
         * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
         * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
         * at the beginning of a line
         * l is of the form l = 2*k, k a non negative integer
         */
        private val ZZ_LEXSTATE = intArrayOf(
            0, 0, 1, 1
        )
        private const val ZZ_CMAP_TOP_PACKED_0 =
            "\u0001\u0000\u001f\u0100\u0001\u0200\u00b7\u0100\u0008\u0300\u1020\u0100"

        /**
         * Top-level table for translating characters to character classes
         */
        private val ZZ_CMAP_TOP = zzUnpackcmap_top()
        private const val ZZ_CMAP_BLOCKS_PACKED_0 =
            "\u0009\u0000\u0001\u0001\u0001\u0002\u0001\u0003\u0001\u0001\u0001\u0002\u0012\u0000\u0001\u0001" +
            "\u0001\u0000\u0001\u0004\u0039\u0000\u0001\u0005\u0005\u0000\u0001\u0006\u0003\u0000\u0001\u0007" +
            "\u0007\u0000\u0001\u0008\u0003\u0000\u0001\u0009\u0001\u0000\u0001\u000a\u0006\u0000\u0001\u000b" +
            "\u0001\u0000\u0001\u000c\u0007\u0000\u0001\u0003\u01a2\u0000\u0002\u0003\u00d6\u0000\u0100\u0003"

        /**
         * Second-level tables for translating characters to character classes
         */
        private val ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks()
        private const val ZZ_ACTION_PACKED_0 =
            "\u0002\u0000\u0001\u0001\u0001\u0002\u0001\u0003\u0001\u0004\u0001\u0005\u0001\u0006\u0001\u0007" +
            "\u0001\u0008\u0001\u0009\u0001\u000a\u0001\u000b\u0001\u000c\u0001\u000d\u0001\u000e"

        /**
         * Translates DFA states to action switch labels.
         */
        private val ZZ_ACTION = zzUnpackAction()
        private const val ZZ_ROWMAP_PACKED_0 =
            "\u0000\u0000\u0000\u000d\u0000\u001a\u0000\u001a\u0000\u001a\u0000\u001a\u0000\u001a\u0000\u0027" +
            "\u0000\u001a\u0000\u0034\u0000\u001a\u0000\u001a\u0000\u001a\u0000\u001a\u0000\u001a\u0000\u001a"

        /**
         * Translates a state to a row index in the transition table
         */
        private val ZZ_ROWMAP = zzUnpackRowMap()
        private const val ZZ_TRANS_PACKED_0 =
            "\u0001\u0003\u0002\u0004\u0001\u0000\u0001\u0005\u0006\u0003\u0001\u0006\u0001\u0007\u0002\u0008" +
            "\u0001\u0000\u0001\u0008\u0001\u0009\u0001\u000a\u0007\u0008\u000d\u0000\u0002\u0008\u0001\u0000" +
            "\u0001\u0008\u0002\u0000\u0007\u0008\u0004\u0000\u0001\u000b\u0001\u0000\u0001\u000c\u0001\u000d" +
            "\u0001\u000e\u0001\u000f\u0001\u0010\u0002\u0000"

        /**
         * The transition table of the DFA
         */
        private val ZZ_TRANS = zzUnpackTrans()

        /**
         * Error code for "Unknown internal scanner error".
         */
        private const val ZZ_UNKNOWN_ERROR = 0

        /**
         * Error code for "could not match input".
         */
        private const val ZZ_NO_MATCH = 1

        /**
         * Error code for "pushback value was too large".
         */
        private const val ZZ_PUSHBACK_2BIG = 2

        /**
         * Error messages for [ZZ_UNKNOWN_ERROR], [ZZ_NO_MATCH], and
         * [ZZ_PUSHBACK_2BIG] respectively.
         */
        private val ZZ_ERROR_MSG = arrayOf(
            "Unknown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
        )
        private const val ZZ_ATTRIBUTE_PACKED_0 =
            "\u0002\u0000\u0005\u0009\u0001\u0001\u0001\u0009\u0001\u0001\u0006\u0009"

        /**
         * ZZ_ATTRIBUTE[aState] contains the attributes of state `aState`
         */
        private val ZZ_ATTRIBUTE = zzUnpackAttribute()

        private fun zzUnpackcmap_top(): IntArray {
            val result = IntArray(4352)
            var offset = 0
            offset = zzUnpackRle(ZZ_CMAP_TOP_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackcmap_blocks(): IntArray {
            val result = IntArray(1024)
            var offset = 0
            offset = zzUnpackRle(ZZ_CMAP_BLOCKS_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackAction(): IntArray {
            val result = IntArray(16)
            var offset = 0
            offset = zzUnpackRle(ZZ_ACTION_PACKED_0, offset, result)
            return result
        }

        /**
         * Run-length unpacking shared by the cmap, action and attribute tables
         * (identical bodies in the generated Java source).
         */
        private fun zzUnpackRle(packed: String, offset: Int, result: IntArray): Int {
            var i = 0       /* index in packed string  */
            var j = offset  /* index in unpacked array */
            val l = packed.length
            while (i < l) {
                var count = packed[i++].code
                val value = packed[i++].code
                do {
                    result[j++] = value
                } while (--count > 0)
            }
            return j
        }

        private fun zzUnpackRowMap(): IntArray {
            val result = IntArray(16)
            var offset = 0
            offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackRowMap(packed: String, offset: Int, result: IntArray): Int {
            var i = 0  /* index in packed string  */
            var j = offset  /* index in unpacked array */
            val l = packed.length
            while (i < l) {
                val high = packed[i++].code shl 16
                result[j++] = high or packed[i++].code
            }
            return j
        }

        private fun zzUnpackTrans(): IntArray {
            val result = IntArray(65)
            var offset = 0
            offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackTrans(packed: String, offset: Int, result: IntArray): Int {
            var i = 0       /* index in packed string  */
            var j = offset  /* index in unpacked array */
            val l = packed.length
            while (i < l) {
                var count = packed[i++].code
                var value = packed[i++].code
                value--
                do {
                    result[j++] = value
                } while (--count > 0)
            }
            return j
        }

        private fun zzUnpackAttribute(): IntArray {
            val result = IntArray(16)
            var offset = 0
            offset = zzUnpackRle(ZZ_ATTRIBUTE_PACKED_0, offset, result)
            return result
        }

        /**
         * Translates raw input code points to DFA table row
         */
        private fun zzCMap(input: Int): Int {
            val offset = input and 255
            return if (offset == input) ZZ_CMAP_BLOCKS[offset] else ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input shr 8] or offset]
        }

        /**
         * Reports an error that occurred while scanning.
         *
         * In a well-formed scanner (no or only correct usage of `yypushback(int)` and a
         * match-all fallback rule) this method will only be called with things that
         * "Can't Possibly Happen".
         *
         * If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
         * scanner etc.).
         *
         * Usual syntax/scanner level error handling should be done in error fallback rules.
         *
         * @param errorCode the code of the error message to display.
         */
        private fun zzScanError(errorCode: Int) {
            val message: String = try {
                ZZ_ERROR_MSG[errorCode]
            } catch (e: ArrayIndexOutOfBoundsException) {
                ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR]
            }

            throw Error(message)
        }

        @JvmStatic
        @Throws(Exception::class)
        fun checkToken(str: String, str2: String) {
            if (str != str2) {
                throw Exception(String.format("Invalid token: expected=%s, got=%s", str2, str))
            }
        }
    }
}
