plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace = 'com.jaredrummler.android.colorpicker'
    compileSdk = rootProject.ext.compileSdkVersion
    resourcePrefix = "cpv_"

    defaultConfig {
        minSdk = rootProject.ext.minSdkVersion
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    lint {
        abortOnError = false
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.recyclerview
    implementation libs.androidx.dynamicanimation
    implementation libs.google.material

    // tests
    testImplementation libs.junit
    androidTestImplementation libs.bundles.android.test
}
